// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gallery/Cinematic.tsx": () => import("../components/mockups/gallery/Cinematic.tsx"),
  "./components/mockups/gallery/DarkRoom.tsx": () => import("../components/mockups/gallery/DarkRoom.tsx"),
  "./components/mockups/gallery/Editorial.tsx": () => import("../components/mockups/gallery/Editorial.tsx")
};
